language: "node_js"

node_js:
  - "12"
  - "10"

cache:
  directories:
    - "node_modules"

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:server --grep ''

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

sudo: false

deploy:
  provider: npm
  email: bring2dip@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
